### ISSUE TITLE
IOS执行报错：Cannot add property toPx, object is not extensible  Android没问题，请帮忙看一下，谢谢

### ISSUE THREAD

**Issue by 452896915** [Kujiale-Mobile/Painter#124]
[publib]:1 thirdScriptError
Cannot add property toPx, object is not extensible; [Component] Lifetime Method Error @ components/painter/painter#attached
TypeError: Cannot add property toPx, object is not extensible
    at setStringPrototype (weapp:///components/painter/painter.js:253:25)
    at Y.attached (weapp:///components/painter/painter.js:53:5)
    at r.safeCallback ([publib]:1:851060)
    at r.call ([publib]:1:850953)
    at r ([publib]:1:923169)
    at r ([publib]:1:923484)
    at r ([publib]:1:923426)
    at S ([publib]:1:923494)
    at Function.m.pretendAttached ([publib]:1:933494)
    at Object.t.attachView ([publib]:1:995864)

**Comment by aetherwu** [comment]
查了一下源代码， 发现tempalte 参数传入的时候必须初始化。有点不够直观/人性化。
> new Card()
> Card.do({})

**Comment by CPPAlien** [comment]
template 是自己选择的哦，你可以用一个不初始化的 template

**Comment by aetherwu** [comment]
@CPPAlien 感谢提示！：D
